name: 🎯 Build and deploy apps to server

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run sshpass commands
        uses: matheusvanzan/sshpass-action@v2
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          user: ${{ secrets.USERNAME }}
          pass: ${{ secrets.PASSWORD }}
          script: |
            cd /aironment-be
            git stash
            git pull origin main
            git status
            go mod tidy
            go build -o main ./cmd/app
            systemctl restart aironment.service
